=== planmap-eu/storymaps/storymap_data/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "required": ["title", "basemap"],
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "planmap_id": {
      "type": "string"
    },
    "publication": {
      "type": "string"
    },
    "authors": {
      "type": "string"
    },
    "basemap": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "minLength": 10
        },
        "options": {
          "type": "object",
          "properties": {
            "crs": {
              "type": "string",
              "enum": ["EPSG3857"]
            },
            "maxNativeZoom": {
              "type": "integer"
            },
            "tms": {
              "type": "boolean"
            },
            "autoZIndex": {
              "type": "boolean"
            },
            "attribution": {
              "type": "string"
            }
          }
        }
      }
    },
    "chapters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "order": {
            "type": "integer"
          },
          "steps": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string"
                },
                "text": {
                  "type": "string"
                },
                "stoptime": {
                  "type": "integer"
                },
                "layers": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "order": {
                        "type": "integer"
                      },
                      "credits": {
                        "type": "string"
                      },
                      "path": {
                        "type": "string"
                      },
                      "owstype": {
                        "type": "string",
                        "enum": ["wms", "wfs"]
                      }
                    }
                  }
                },
                "media": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "path": {
                        "type": "string"
                      },
                      "mimetype": {
                        "type": "string",
                        "enum": ["video/youtube", "image/png", "model/gltf-binary"]
                      },
                      "caption": {
                        "type": "string"
                      }
                    }
                  }
                },
                "view": {
                  "type": "object",
                  "properties": {
                    "extent": {
                      "type": "array",
                      "minItems": 4,
                      "maxItems": 4,
                      "items": [
                        {
                          "type": "number",
                          "minimum": -180,
                          "maximum": 180
                        },
                        {
                          "type": "number",
                          "minimum": -90,
                          "maximum": 90
                        },
                        {
                          "type": "number",
                          "minimum": -180,
                          "maximum": 180
                        },
                        {
                          "type": "number",
                          "minimum": -90,
                          "maximum": 90
                        }
                      ]
                    },
                    "marker": {
                      "type": "array",
                      "items": [
                        {
                          "type": "number",
                          "minimum": -180,
                          "maximum": 180,
                          "exclusiveMinimum": true,
                          "exclusiveMaximum": true
                        },
                        {
                          "type": "number",
                          "minimum": -90,
                          "maximum": 90,
                          "exclusiveMinimum": true,
                          "exclusiveMaximum": true
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== planmap-eu/storymaps/storymap_data/moon/spaapollo_storymap_data.json
{
  "title": "SPA Apollo",
  "authors": "Misha Ivanov et al.,",
  "basemap": {
    "url": "https://cartocdn-gusc.global.ssl.fastly.net/opmbuilder/api/v1/map/named/opm-mars-basemap-v0-1/0,1,2,3,4/{z}/{x}/{y}.png",
    "options": {
      "crs": "EPSG3857",
      "maxNativeZoom": 9,
      "tms": false,
      "autoZIndex": true,
      "attribution": "<a href='https://github.com/openplanetary/opm/wiki/OPM-Basemaps' target='_blank'>OpenPlanetaryMap</a>"
    }
  },
  "chapters": [
    {
      "order": 1,
      "steps": [
        {
          "title": "Why mapping Mars today?",
          "text": "Looking for the geological past of Mars is important for us for several reasons: understand what happens on Mars, and how this planet differs from ours? Did Life emerge at its surface, and if yes, for how long? Are Life-compliant conditions still present somewhere on Mars? And of course, to prepare future manned exploration missions: where to land safely and make the most science? Thatâ€™s where geological mapping comes into play",        "media:": "",
          "view": {
            "extent": [-180, -90, 180, 90]
          },
          "layers": [
            {
              "credits": "https://data.planmap.eu/pub/moon/PM-MOO-MS-SPAApollo_01/",
              "order": 1,
              "path": "moon:PM-MOO-MS-SPAApollo_01_Apl_large_crater_rims",
              "type": "wms"
            },
            {
              "credits": "https://data.planmap.eu/pub/moon/PM-MOO-MS-SPAApollo_01/",
              "order": 2,
              "path": "moon:PM-MOO-MS-SPAApollo_01_Apl_graben",
              "type": "wms"
            },
            {
              "credits": "https://data.planmap.eu/pub/moon/PM-MOO-MS-SPAApollo_01/",
              "order": 3,
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Apollo_rimt",
              "type": "wms"
            },
            {
              "credits": "https://data.planmap.eu/pub/moon/PM-MOO-MS-SPAApollo_01/",
              "order": 4,
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full",
              "type": "wms"
            }
          ],
          "view": {
            "extent": [-180, -62.6, -7.7, 90]
          }
        }
      ]
    },
    {
      "order": 2,
      "steps": [
        {
          "text": "The crater Wilsing C (32 km diameter) has a sharp-crested rim, but no discernable ejecta or rays. It is classified as Eratosthenian in age.",
          "title": "Ec - Eratosthenian Craters",
          "layers": [
            {
              "credits": "https://data.planmap.eu/pub/moon/PM-MOO-MS-SPAApollo_01/",
              "order": 1,
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT Ec - Eratosthenian Craters",
              "type": "wms"
            }
          ],
          "view": {
            "extent": [-150.9, -19.5, -154.9, -17.5],
            "marker": [ -152.9, -18.5 ]
          }
        }
      ]
    },
    {
      "order": 3,
      "steps": [
        {
          "text": "Dryden crater (52 km diameter) exhibits discernable ejecta, but no rays. It has a crater size-frequency distribution that indicated it is Upper Imbrian in age.",
          "title": "UIc - Upper Imbrian Craters",
          "layers": [
            {
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT UIc - Upper Imbrian Craters",
              "type": "wms"
            }
          ],
          "view": {
            "extent": [-158, -34, -154, -32],
            "marker": [ -156, -33 ]
          }
        }
      ]
    },
    {
      "order": 4,
      "steps": [
        {
          "layers": [
            {
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT LIo - Orientale sculpted terrain",
              "type": "wms"
            }
          ],
          "text": "Secondary crater chains and grooves that originate from Orientale basin are present on the eastern side of the mapping area, and are Lower Imbrian in age.",
          "title": "LIo - Orientale sculpted terrain",
          "view": {
            "extent": [-131.1, -50.8, -127.1, -48.8],
            "marker": [ -129.1, -49.8]
          }
        }
      ]
    },
    {
      "order": 5,
      "steps": [
        {
          "layers": [
            {
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT LIc - Lower Imbrian craters",
              "type": "wms"
            }
          ],
          "text": "Fizeau crater has a crater size-frequency distribution that places it as having a Lower Imbrian age.",
          "title": "LIc - Lower Imbrian craters",
          "view": {
            "extent": [-135.9, -59, -132.9, -57],
            "marker": [-133.9, -58 ]
          }
        }
      ]
    },
    {
      "order": 6,
      "steps": [
        {
          "layers": [
            {
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT Ip - Imbrian planins",
              "type": "wms"
            }
          ],
          "text": "Smooth, light-colored deposits called light plains fill craters and hollows in some locations within the mapping area. These are Upper Imbrian in age.",
          "title": "Ip - Imbrian plains",
          "view": {
            "extent": [-171.5, -24.6, -167.5, -22.6],
            "marker": [-169.5, -23.6]
          }
        }
      ]
    },
    {
      "order": 7,
      "steps": [
        {
          "text": "The dark, smooth plains deposits mapped in this area primarily include mare basalts within Apollo basin and to the southwest towards the center of the South Pole-Aitken basin. These plains are Upper Imbrian in age.",
          "title": "UIdp - Uppper Imbrian dark plains",
          "view": {
            "extent": [-154, -37, -150, -35],
            "marker": [-152, -36]
          }
        }
      ]
    },
    {
      "order": 8,
      "steps": [
        {
          "layers": [
            {
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT UIlp - Upper Imbrian light plains",
              "type": "wms"
            }
          ],
          "text": "Some light plains with Upper Imbrian ages similar to the dark plains are also mapped in Apollo basin and towards the center of the South Pole-Aitken basin.",
          "title": "UIlp - Upper Imbrian light plains",
          "view": {
            "extent": [-157, -46, -153, -44],
            "marker": [-155, -45]
          }
        }
      ]
    },
    {
      "order": 9,
      "steps": [
        {
          "layers": [
            {
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT LIrp - Lower Imbrian rugged plains",
              "type": "wms"
            }
          ],
          "text": "Low relief, rugged plains have a more rugged appearance than the smooth light and dark plains. These plains appear towards the center of the South Pole-Aitken basin in the southwest corner of the mapping area and are Lower Imbrian in age.",
          "title": "LIrp - Lower Imbrian rugged plains",
          "view": {
            "extent": [-162, -57, -158, -55],
            "marker": [-160, -56]
          }
        }
      ]
    },
    {
      "order": 10,
      "steps": [
        {
          "layers": [
            {
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT NpNc - Nectarian, pre-Nectarian craters",
              "type": "wms"
            }
          ],
          "text": "Many larger craters and basins are Nectarian and pre-Nectarian in age. These form the bulk of the mapping area. For example, Langmuir crater (85 km diameter).",
          "title": "NpNc - Nectarian, pre-Nectarian craters",
          "view": {
            "extent": [-130.8, -36.8, -126.8, -35.8],
            "marker": [-128.8, -35.8]
          }
        }
      ]
    },
    {
      "order": 11,
      "steps": [
        {
          "layers": [
            {
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT pNrmAPL - pre-Nectarian Apollo rim massifs",
              "type": "wms"
            }
          ],
          "text": "The Apollo basin rim and central peak ring massifs are pre-Nectarian in age.",
          "title": "pNrmAPL - pre-Nectarian Apollo rim massifs",
          "view": {
            "extent": [-140, -33.5, -136, -31.5],
            "marker": [-138, -32.5]
          }
        }
      ]
    },
    {
      "order": 12,
      "steps": [
        {
          "layers": [
            {
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT pNlrAPL - pre-Nectarian Apollo low rugged terrains",
              "type": "wms"
            }
          ],
          "text": "Low relief, rugged materials present between the Apollo basin rim and central peak ring massifs are also pre-Nectarian in age and may represent impact material originating from the formation of Apollo basin.",
          "title": "pNlrAPL - pre-Nectarian Apollo low rugged terrains",
          "view": {
            "extent": [-148, -39.6, -144, -37.6],
            "marker": [-146, -38.6]
          }
        }
      ]
    },
    {
      "order": 13,
      "steps": [
        {
          "layers": [
            {
              "path": "geoserver/wms/moon:PM-MOO-MS-SPAApollo_01_Apl_Strat_full - ONLY UNIT pNmSPAf - pre-Nectarian SPA floor material",
              "type": "wms"
            }
          ],
          "text": "Low relief, rugged materials present inside the South Pole-Aitken basin rim massifs on the basin floor are also pre-Nectarian in age, but is distinguishable from the low relief, rugged materials within Apollo basin.",
          "title": "pNmSPAf - pre-Nectarian SPA floor material",
          "view": {
            "extent": [-162.5, -29, -158.5, -27],
            "marker": [-160.5, -28]
          }
